### ISSUE TITLE
Content that is larger than `elasticsearch.bulk_api.max_size_bytes` is not ingested

### ISSUE THREAD

**Issue by navarone-feekery** [elastic/crawler#129]
## Bug Description

The ES bulk queue has a configurable max byte-size limit, set by the field `elasticsearch.bulk_api.max_size_bytes`.
If a document is larger than this value, it won't be ingested at all.
This is very noticable when crawling large binary files.

Here is an example of the error that is output:

```
[crawl:66d87d24c78889fe3de1ae65] [primary] Operation failed to add to bulk queue. Current operation count is 0. Operation payload was 8853814 bytes, current buffer size is 0 bytes.
[crawl:66d87d24c78889fe3de1ae65] [primary] Unexpected exception while sending crawl results to the output sink: Errors::BulkQueueOverflowError
```

### To Reproduce
1. Crawl a site with a large binary file (e.g. `https://princexml.com`
2. See the above error
3. See that the file was not ingested

## Expected behavior

Even files larger than the bulk overflow size should be ingested, just as a single request.

**Comment by seanstory** [comment]
We could log a more informative and actionable warning, but I think this is expected. If the doc is too big, it's too big. There's not a lot we can do for you (until we add an integration with the Data Extraction Service).

**Comment by navarone-feekery** [comment]
@seanstory I can see an argument for leaving it as it is, but I never personally considered the bulk queue byte threshold to be a limit for content size to index into Elasticsearch. It was just supposed to limit the size of the bulk request so it wouldn't grow too large. So my concern here is that the configuration is limiting the wrong thing right now.

Even with integrating with the data extraction service, the `elasticsearch.bulk_api.max_size_bytes` will limit large files from being ingested unless it's significantly increased.

I think there should be another configuration for "max doc size" or something that cannot go over the Elasticsearch request size limit.

**Comment by navarone-feekery** [comment]
Closing this as not an actual bug.
