### ISSUE TITLE
Inconsistent number of items / docs indexed in logs

### ISSUE THREAD

**Issue by jedrazb** [elastic/crawler#40]
## Bug Description

Run a sync, at the end of the sync you will see sth like

```
[crawl:66597de5d8a03189d1ea00bb] [primary] Crawl queue is empty, finishing the crawl
[crawl:66597de5d8a03189d1ea00bb] [primary] Closing the output sink before finishing the crawl...
[crawl:66597de5d8a03189d1ea00bb] [primary] Sending bulk request with 66 items and flushing queue...
[crawl:66597de5d8a03189d1ea00bb] [primary] No errors found in bulk response.
[crawl:66597de5d8a03189d1ea00bb] [primary] Bulk request containing 66 items sent!
[crawl:66597de5d8a03189d1ea00bb] [primary] {:indexed_document_count=>33, :indexed_document_volume=>269066}
```

You will see `Sending bulk request with 66 items` while the actual indexed doc count is 33.

That log statement might confuse users.

## Expected behavior

- Bulk request payload should match indexed doc count

## Environment

Docker built locally

**Comment by navarone-feekery** [comment]
This was resolved in https://github.com/elastic/crawler/pull/39, numbers are consistent now
