### ISSUE TITLE
change "body_content" field name to "body"

### ISSUE THREAD

**Issue by pezzking** [elastic/crawler#48]
### Problem Description
1. field is not consistent with body field used by elastic connector framework, which uses "body" field
2. using elasticsearch.pipeline: ent-search-generic-ingestion as default pipeline works on body field and not body_content

### Proposed Solution
change the field from body_content to body throughout the code.

**Comment by seanstory** [comment]
This is a great call, and this is a good time for us to get these aligned, since there are currently no UIs or APIs expecting the field name to be `body_content`

**Comment by navarone-feekery** [comment]
Thanks @pezzking for bringing this up. It will be changed in v0.2.0 (beta).

**Comment by CobusT** [comment]
Has this been fixed in v0.2.0? I still see `body_content` in the ES documents generated when running v0.2.0.

**Comment by seanstory** [comment]
@CobusT v0.2.0 isn't released yet, but is the version on main. You should be able to pull the latest to get the change. The linked PR was merged into main two weeks ago.

**Comment by CobusT** [comment]
Thanks. Yup, I have since pulled the new main and saw the change.
